import type { Category, Product, HeroBanner, Coupon, StoreSettings } from './types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: "ZOHAN TRADERS",
  tagline: "Your Trusted Partner for Security, IT & Construction Solutions",
  phone: "+92333-8586852",
  whatsapp: "923338586852",
  email: "traderszohan@gmail.com",
  address: "Jampur Road, DG Khan, Pakistan",
  googleMapsUrl: "https://maps.app.goo.gl/qRNjuofwZ9iXcyUVA",
  ntn: "7539474-3",
  strn: "3277876288512",
  baseShippingFee: 250,
  freeShippingThreshold: 5000,
  codEnabled: true,
  jazzCash: {
    accountTitle: "Zohan Traders DG Khan",
    accountNumber: "03338586852",
    instruction: "Transfer to JazzCash 0333-8586852 and share transaction ID / screenshot on WhatsApp for instant confirmation.",
  },
  easyPaisa: {
    accountTitle: "Zohan Traders DG Khan",
    accountNumber: "03338586852",
    instruction: "Transfer to EasyPaisa 0333-8586852 and share transaction ID / screenshot on WhatsApp for instant confirmation.",
  },
  bankTransfer: {
    bankName: "Meezan Bank Limited",
    accountTitle: "Zohan Traders",
    accountNumber: "01010102030405",
    iban: "PK36MEZN0001010102030405",
    branch: "Jampur Road Branch, DG Khan",
  },
  currency: "PKR",
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-construction",
    name: "RAW MATERIAL OF CONSTRUCTION",
    slug: "construction",
    description: "Premium grade building supplies, Multani clay bricks, tuff tiles, marble, sanitaryware, and structural supplies.",
    image: "https://images.unsplash.com/photo-1541888946425-d0fbb18615f8?q=80&w=1000&auto=format&fit=crop",
    icon: "Hammer",
    subcategories: [
      { id: "sub-bricks", categoryId: "cat-construction", name: "Multani Clay Bricks & Tuff Tiles", slug: "multani-clay-bricks-tuff-tiles" },
      { id: "sub-alum-glass", categoryId: "cat-construction", name: "Aluminium & Glass", slug: "aluminium-glass" },
      { id: "sub-tiles-marble", categoryId: "cat-construction", name: "Tiles & Marble", slug: "tiles-marble" },
      { id: "sub-wooden", categoryId: "cat-construction", name: "Wooden Materials", slug: "wooden-materials" },
      { id: "sub-sanitary", categoryId: "cat-construction", name: "Sanitary Items", slug: "sanitary-items" },
      { id: "sub-sands", categoryId: "cat-construction", name: "Sands", slug: "sands" },
    ],
  },
  {
    id: "cat-stationery",
    name: "OFFICE STATIONERY",
    slug: "stationery",
    description: "Bulk corporate stationery, legal printing sheets, heavy-duty organizers, premium pens, and archival folders.",
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=1000&auto=format&fit=crop",
    icon: "BookOpen",
    subcategories: [
      { id: "sub-pens-paper", categoryId: "cat-stationery", name: "Pens & Paper", slug: "pens-paper" },
      { id: "sub-organizers", categoryId: "cat-stationery", name: "Desk Organizers", slug: "desk-organizers" },
      { id: "sub-filing", categoryId: "cat-stationery", name: "Filing & Folders", slug: "filing-folders" },
      { id: "sub-printing", categoryId: "cat-stationery", name: "Printing Materials", slug: "printing-materials" },
    ],
  },
  {
    id: "cat-it",
    name: "IT PRODUCTS",
    slug: "it-products",
    description: "Enterprise networking equipment, fiber optics, enterprise wireless backhauls, switches, and workstations.",
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1000&auto=format&fit=crop",
    icon: "Server",
    subcategories: [
      { id: "sub-laptops", categoryId: "cat-it", name: "Laptops & Computers", slug: "laptops-computers" },
      { id: "sub-switches", categoryId: "cat-it", name: "Network Switches", slug: "network-switches" },
      { id: "sub-fiber", categoryId: "cat-it", name: "Fiber Cables & Accessories", slug: "fiber-cables-accessories" },
      { id: "sub-catcables", categoryId: "cat-it", name: "CAT6/CAT7 Cables", slug: "cat6-cat7-cables" },
      { id: "sub-wireless", categoryId: "cat-it", name: "Wireless Communication Litebeam/Powerbeam/Air Fiber", slug: "wireless-communication" },
    ],
  },
  {
    id: "cat-security",
    name: "SECURITY",
    slug: "security",
    description: "Complete perimeter and physical defense solutions: CCTV cameras, walkthrough gates, biometric access, and fire alarms.",
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1000&auto=format&fit=crop",
    icon: "ShieldAlert",
    subcategories: [
      { id: "sub-cctv", categoryId: "cat-security", name: "CCTV Cameras", slug: "cctv-cameras" },
      { id: "sub-walkthrough", categoryId: "cat-security", name: "Walkthrough Gates", slug: "walkthrough-gates" },
      { id: "sub-safety", categoryId: "cat-security", name: "Safety Wear", slug: "safety-wear" },
      { id: "sub-firealarm", categoryId: "cat-security", name: "Fire Alarm Systems", slug: "fire-alarm-systems" },
      { id: "sub-access", categoryId: "cat-security", name: "Access Control", slug: "access-control" },
      { id: "sub-razor", categoryId: "cat-security", name: "Razor Wire", slug: "razor-wire" },
      { id: "sub-fencing", categoryId: "cat-security", name: "Electric Fencing", slug: "electric-fencing" },
    ],
  },
  {
    id: "cat-furniture",
    name: "OFFICE FURNITURE",
    slug: "office-furniture",
    description: "Ergonomic executive chairs, modern modular workstations, durable wooden flooring, and secure archive cabinets.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop",
    icon: "Armchair",
    subcategories: [
      { id: "sub-workstations", categoryId: "cat-furniture", name: "Workstations", slug: "workstations" },
      { id: "sub-conference", categoryId: "cat-furniture", name: "Conference Room Furniture", slug: "conference-room-furniture" },
      { id: "sub-flooring", categoryId: "cat-furniture", name: "Wooden Flooring", slug: "wooden-flooring" },
      { id: "sub-chairs", categoryId: "cat-furniture", name: "Office Chairs", slug: "office-chairs" },
      { id: "sub-cabinets", categoryId: "cat-furniture", name: "Cabinets", slug: "cabinets" },
    ],
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // SECURITY
  {
    id: "prod-hik-4k-cctv",
    name: "Hikvision 4K Ultra HD IP Bullet CCTV Camera",
    slug: "hikvision-4k-ultra-hd-ip-bullet-cctv",
    categoryId: "cat-security",
    subcategoryId: "sub-cctv",
    price: 18500,
    salePrice: 16200,
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1580983561371-7f4b242d8ec0?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Commercial-grade 8MP 4K IP Bullet camera featuring ColorVu night vision, built-in dual microphone, H.265+ high efficiency compression, and IP67 weather resistance. Perfect for banks, hospitals, and corporate premises.",
    specifications: {
      "Resolution": "8 Megapixel (3840 × 2160)",
      "Night Vision Range": "Up to 40m Full Color",
      "Lens": "2.8mm / 4mm fixed lens",
      "Protection": "IP67 Weatherproof & IK10 Vandal-Proof",
      "Warranty": "12 Months Official Zohan Replacement Warranty",
    },
    features: [
      "Acusense deep learning human & vehicle classification",
      "24/7 vivid color imaging even in zero light",
      "Active strobe light and audio alarm warning",
      "Seamless integration with NVR and mobile remote monitoring",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN E-SECURITY",
    brand: "Hikvision",
    created_at: "2026-09-20T10:00:00Z",
  },
  {
    id: "prod-zkteco-walkthrough",
    name: "ZKTeco D3180S 18-Zone Walkthrough Metal Detector Gate",
    slug: "zkteco-d3180s-18-zone-walkthrough-metal-detector-gate",
    categoryId: "cat-security",
    subcategoryId: "sub-walkthrough",
    price: 175000,
    salePrice: 159000,
    stock: 8,
    images: [
      "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1508847154043-be5407fcaa5a?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-sensitivity 18 independent detection zones security gate with 7-inch LCD interface. Displays count of people passing and alarm records. Fully compliant with international airport and bank security protocols.",
    specifications: {
      "Detection Zones": "18 Overlapping Zones",
      "Sensitivity Levels": "256 Adjustable Levels per zone",
      "Display": "7-inch HD LCD Control Screen",
      "Throughput Rate": "Up to 60 persons per minute",
      "Standard Compliance": "CE / FCC / RoHS / ISO9001",
    },
    features: [
      "Simultaneous multi-location pinpoint detection",
      "Tamper-proof password protection on settings",
      "Harmless to heart pacemakers and magnetic media",
      "Backup power battery ready (optional battery pack)",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN E-SECURITY",
    brand: "ZKTeco",
    created_at: "2026-09-18T14:30:00Z",
  },
  {
    id: "prod-zkteco-biometric",
    name: "ZKTeco ProFace X Biometric Face & Palm Access Control",
    slug: "zkteco-proface-x-biometric-access-control",
    categoryId: "cat-security",
    subcategoryId: "sub-access",
    price: 85000,
    salePrice: 79500,
    stock: 14,
    images: [
      "https://images.unsplash.com/photo-1508847154043-be5407fcaa5a?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Enterprise anti-spoofing facial recognition terminal with palm verification and RFID card reader. IP68 waterproof design with 50,000 face capacity and lightning-fast 0.3s match speed.",
    specifications: {
      "Face Capacity": "50,000 Faces",
      "Palm Capacity": "5,000 Palms",
      "Recognition Speed": "< 0.3 seconds",
      "Interface": "TCP/IP, Wiegand Input/Output, RS485",
      "Protection": "IP68 Water & Dust Proof, IK04 Vandal",
    },
    features: [
      "Mask detection & temperature screening ready",
      "Anti-spoofing algorithm against photo and video attacks",
      "Integrated door relay control for magnetic locks",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN E-SECURITY",
    brand: "ZKTeco",
    created_at: "2026-09-15T09:00:00Z",
  },

  // IT PRODUCTS & NETWORKS
  {
    id: "prod-ubiquiti-litebeam",
    name: "Ubiquiti LiteBeam 5AC Gen2 23dBi Outdoor Wireless Bridge",
    slug: "ubiquiti-litebeam-5ac-gen2-23dbi",
    categoryId: "cat-it",
    subcategoryId: "sub-wireless",
    price: 24500,
    salePrice: 22800,
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-performance airMAX ac 5GHz 23dBi directional CPE bridge delivering 450+ Mbps throughput over long-range line-of-sight wireless links. Ideal for campus interconnectivity, remote site CCTV backhaul, and ISP links.",
    specifications: {
      "Frequency Band": "5 GHz (airMAX ac)",
      "Antenna Gain": "23 dBi innerfeed",
      "Throughput": "450+ Mbps Real TCP/IP",
      "Range": "Up to 25+ KM line of sight",
      "Power Method": "24V, 0.3A Gigabit PoE (Included)",
    },
    features: [
      "Dedicated Wi-Fi management radio for quick smartphone setup",
      "Die-cast aluminum antenna bracket with 3-axis alignment",
      "Robust ESD and surge protection up to 24kV",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN NETWORKS",
    brand: "Ubiquiti Networks",
    created_at: "2026-09-21T11:00:00Z",
  },
  {
    id: "prod-fast-cat6-drum",
    name: "Fast Cables Pure Copper CAT6 UTP Network Cable (305m Roll)",
    slug: "fast-cables-pure-copper-cat6-utp-roll-305m",
    categoryId: "cat-it",
    subcategoryId: "sub-catcables",
    price: 32000,
    salePrice: 29500,
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Certified 100% solid oxygen-free bare copper 23 AWG 4-pair unshielded twisted pair (UTP) network cable roll. Meets TIA/EIA 568-C.2 standards for gigabit structured cabling infrastructure.",
    specifications: {
      "Conductor": "100% Solid Pure Copper 23 AWG",
      "Bandwidth": "250 MHz / 1000 Mbps Gigabit Ethernet",
      "Roll Length": "305 Meters (1000 Feet) Pull Box",
      "Jacket": "Flame-Retardant PVC / LSZH Compliant",
      "Certification": "Fluke Channel Test Verified",
    },
    features: [
      "Zero signal degradation across long structural runs",
      "High density PE insulation with internal spline separator",
      "Sequential meter markers on jacket for easy measurement",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN NETWORKS",
    brand: "Fast Cables",
    created_at: "2026-09-17T08:15:00Z",
  },
  {
    id: "prod-dlink-24port-poe",
    name: "D-Link 24-Port Gigabit Smart Managed PoE+ Switch",
    slug: "d-link-24-port-gigabit-smart-managed-poe-switch",
    categoryId: "cat-it",
    subcategoryId: "sub-switches",
    price: 95000,
    salePrice: 88000,
    stock: 12,
    images: [
      "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Commercial rackmount 24-port 10/100/1000 PoE+ switch with 4 combo SFP uplink slots. 370W total power budget supporting IP cameras, access points, and VoIP phones with VLAN and QoS traffic management.",
    specifications: {
      "Ports": "24 x 10/100/1000BASE-T PoE+ & 4 x SFP Ports",
      "PoE Budget": "370 Watts (Up to 30W per port)",
      "Switching Capacity": "56 Gbps",
      "Form Factor": "1U 19-inch Rackmountable Steel Chassis",
    },
    features: [
      "Surge protection on all Ethernet ports",
      "Intuitive web management GUI + CLI control",
      "Automatic surveillance VLAN prioritization",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN NETWORKS",
    brand: "D-Link",
    created_at: "2026-09-19T13:00:00Z",
  },

  // RAW MATERIAL OF CONSTRUCTION
  {
    id: "prod-multani-bricks",
    name: "First Class Red Multani Clay Bricks (Awal Quality - 1000 Pcs)",
    slug: "first-class-red-multani-clay-bricks-awal-quality",
    categoryId: "cat-construction",
    subcategoryId: "sub-bricks",
    price: 16500,
    salePrice: 15500,
    stock: 200,
    images: [
      "https://images.unsplash.com/photo-1541888946425-d0fbb18615f8?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Genuine high-density kiln-fired Multani clay bricks. Uniform rectangular shapes, metallic ringing sound, and high compressive strength. Extensively supplied to institutional construction projects across South Punjab.",
    specifications: {
      "Grade": "Awal Class (First Quality Kiln Fired)",
      "Standard Size": "9\" x 4.5\" x 3\"",
      "Compressive Strength": "Exceeds 2500 PSI",
      "Water Absorption": "< 12%",
      "Minimum Order": "1,000 Pieces (Bulk Tipper Deliveries Available)",
    },
    features: [
      "Zero salt petre (efflorescence) guarantee",
      "Extreme thermal insulation for hot summer climates",
      "Precise sharp edges for clean masonry work",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Zohan Construction Supplies",
    created_at: "2026-09-22T08:00:00Z",
  },
  {
    id: "prod-tuff-tiles-heavy",
    name: "Industrial Interlocking Tuff Tiles 60mm & 80mm",
    slug: "industrial-interlocking-tuff-tiles-heavy-duty",
    categoryId: "cat-construction",
    subcategoryId: "sub-bricks",
    price: 75,
    salePrice: 68,
    stock: 5000,
    images: [
      "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Hydraulic press vibro-compacted interlocking tuff tiles for commercial parking areas, petrol pumps, driveways, and municipal walkways. Available in multiple color combinations (Red, Charcoal, Yellow). Price per sq. ft.",
    specifications: {
      "Thickness Options": "60mm (Light-Medium Traffic) / 80mm (Heavy Truck Traffic)",
      "Strength": "4000+ PSI Hydraulic Compaction",
      "Surface Finish": "Non-skid textured top layer",
    },
    features: [
      "Heavy load bearing capacity without sinking or cracking",
      "Easy maintenance and removable for underground service work",
      "Weather-proof UV-stable mineral color pigments",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Zohan Construction Supplies",
    created_at: "2026-09-16T15:20:00Z",
  },
  {
    id: "prod-sanitary-luxury",
    name: "Master Ceramic One-Piece Luxury Water Closet & Vanity Basin",
    slug: "master-ceramic-luxury-sanitary-set",
    categoryId: "cat-construction",
    subcategoryId: "sub-sanitary",
    price: 38000,
    salePrice: 34500,
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Vitreous china glaze sanitary suite featuring dual-flush water-saving siphon mechanism, soft-closing hydraulic seat cover, and antibacterial nano-coating for hygiene and effortless cleaning.",
    specifications: {
      "Material": "Grade A Vitreous China Ceramic",
      "Flushing System": "Tornado Siphon Dual Flush (3L / 6L)",
      "Rough-in Distance": "300mm Bottom Outlet",
      "Warranty": "5-Year Ceramic Glaze Guarantee",
    },
    features: [
      "Nano-glazed surface prevents limescale and stain build-up",
      "Whisper-quiet soft closing seat and cover",
      "Engineered for high water efficiency",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Master Sanitary",
    created_at: "2026-09-14T11:00:00Z",
  },

  // OFFICE STATIONERY
  {
    id: "prod-paper-a4-box",
    name: "Double A Premium 80GSM A4 Copier Paper (Box of 5 Reams)",
    slug: "double-a-premium-80gsm-a4-box-5-reams",
    categoryId: "cat-stationery",
    subcategoryId: "sub-pens-paper",
    price: 6800,
    salePrice: 6200,
    stock: 150,
    images: [
      "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-grade 80 GSM ultra-white multipurpose photocopy and laser printing paper. Jam-free performance across high-speed digital xerox machines, inkjet, and laser printers. Box contains 5 reams (2,500 sheets total).",
    specifications: {
      "Weight": "80 GSM Heavyweight",
      "Brightness": "106% High Whiteness",
      "Sheet Count": "500 Sheets per ream (2,500 Sheets per Box)",
      "Sheet Size": "A4 (210 x 297 mm)",
      "Compatibility": "Laser, Inkjet, Offset, and Photocopier",
    },
    features: [
      "Zero paper curl and exceptional opacity for double-sided printing",
      "Acid-free archival paper preventing yellowing over decades",
      "Smooth micro-fiber surface extends copier drum lifespan",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN STATIONARY",
    brand: "Double A",
    created_at: "2026-09-22T09:30:00Z",
  },
  {
    id: "prod-deli-organizer",
    name: "Deli Multi-Tier Metal Mesh Desktop Document Organizer",
    slug: "deli-metal-mesh-desktop-document-organizer",
    categoryId: "cat-stationery",
    subcategoryId: "sub-organizers",
    price: 3200,
    salePrice: 2850,
    stock: 65,
    images: [
      "https://images.unsplash.com/photo-1507842229451-79731e71a805?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Sturdy powder-coated industrial steel mesh 4-tier pull-out sliding tray desk organizer with side pen holder and memo compartment. Keeps office records organized and desks clutter-free.",
    specifications: {
      "Material": "Reinforced Powder-Coated Metal Mesh",
      "Tiers": "4 Pull-out Sliding File Trays + Top Shelf",
      "Dimensions": "35cm x 29cm x 32cm",
      "Color": "Matte Executive Black",
    },
    features: [
      "Rust-resistant finish with non-slip rubberized feet",
      "Easy assembly without special tools",
      "Supports heavy legal files and ledger books",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN STATIONARY",
    brand: "Deli",
    created_at: "2026-09-18T16:00:00Z",
  },

  // OFFICE FURNITURE
  {
    id: "prod-executive-ergonomic-chair",
    name: "Interwood Orthopedic High-Back Executive Mesh Office Chair",
    slug: "interwood-orthopedic-high-back-executive-office-chair",
    categoryId: "cat-furniture",
    subcategoryId: "sub-chairs",
    price: 34500,
    salePrice: 29800,
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1580481077195-c3a821a58875?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Premium ergonomic executive chair with adjustable 3D lumbar support, breathable Korean mesh back, multi-angle tilt lock mechanism, and Class-4 heavy duty hydraulic gas lift. Certified for 8+ hours comfortable daily posture.",
    specifications: {
      "Base": "Heavy-duty 350mm Aluminum Alloy Star Base",
      "Gas Lift": "Class 4 SGS Certified Hydraulic Piston",
      "Weight Capacity": "Tested for up to 150 kg",
      "Armrests": "3D Adjustable (Height, Angle, Depth)",
      "Warranty": "24 Months Structural & Hydraulic Warranty",
    },
    features: [
      "Synchro-tilt recline with 4-stage locking position",
      "Breathable high-tensile mesh prevents back perspiration",
      "High density molded foam seat cushion",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-22T07:15:00Z",
  },
  {
    id: "prod-modular-workstation-4p",
    name: "Executive 4-Person Modular Office Workstation Cluster",
    slug: "executive-4-person-modular-office-workstation-cluster",
    categoryId: "cat-furniture",
    subcategoryId: "sub-workstations",
    price: 145000,
    salePrice: 128000,
    stock: 6,
    images: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Contemporary 4-seater modular desk system built with high-grade Melamine laminated board and powder-coated steel frame. Equipped with integrated wire raceway, modesty acoustic fabric dividers, and individual lockable drawers.",
    specifications: {
      "Configuration": "4-Person Back-to-Back Workstation",
      "Top Board": "25mm Thick Anti-Scratch Melamine Faced Chipboard",
      "Divider Screen": "Framed Fabric Acoustic Tackable Board",
      "Cable Management": "Built-in under-desk raceway with brush grommets",
    },
    features: [
      "Modular expansion ready (can extend to 6 or 8 persons)",
      "Includes 4 mobile 3-drawer lockable pedestals",
      "Heavy gauge triangular steel leg supports",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-17T12:00:00Z",
  },
  {
    id: "prod-industrial-safety-wear-kit",
    name: "Zohan Industrial High-Visibility Safety Wear & PPE Protection Kit",
    slug: "zohan-industrial-safety-wear-ppe-kit",
    categoryId: "cat-security",
    subcategoryId: "sub-safety",
    price: 8500,
    salePrice: 7500,
    stock: 120,
    images: [
      "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Complete institutional personal protective equipment (PPE) bundle including ANSI-certified hard hat, high-luminescence reflective safety vest, steel-toe construction work boots, and cut-resistant Kevlar gloves.",
    specifications: {
      "Certification": "ANSI Z89.1 / EN 397 Industrial Helmet",
      "Vest Standard": "Class 2 High-Visibility 3M Reflective Strip",
      "Boots Protection": "200J Impact Steel Toe Cap & Anti-Piercing Midsole",
      "Contents": "Helmet + Vest + Boots + Safety Goggles + Gloves",
    },
    features: [
      "Impact absorbing high-density ABS shell with 6-point suspension",
      "Waterproof oil-resistant breathable safety footwear",
      "Essential compliance gear for manufacturing plants and civil construction sites",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN E-SECURITY",
    brand: "ZKTeco",
    created_at: "2026-09-19T09:00:00Z",
  },
  {
    id: "prod-addressable-fire-alarm-system",
    name: "EN54 Intelligent Addressable Fire Alarm Panel & Optical Smoke Detector Kit",
    slug: "intelligent-addressable-fire-alarm-control-panel-kit",
    categoryId: "cat-security",
    subcategoryId: "sub-firealarm",
    price: 125000,
    salePrice: 112000,
    stock: 15,
    images: [
      "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Multi-loop institutional fire alarm control system with LCD diagnostic console, battery backup, and 16 addressable photoelectric smoke and thermal heat detectors for corporate offices, hospitals, and bank vaults.",
    specifications: {
      "Standard": "EN54-2 & EN54-4 European Certified",
      "Capacity": "2 Loops (Up to 250 addressable points per loop)",
      "Backup Power": "Dual 12V 7Ah sealed lead-acid standby batteries",
      "Display": "128x64 Graphic Backlit LCD Screen",
    },
    features: [
      "Precision room-level location reporting on emergency events",
      "Built-in 85dB alert horn strobe and manual break-glass call points",
      "Auto-diagnostic sensor drift compensation preventing false alarms",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN E-SECURITY",
    brand: "ZKTeco",
    created_at: "2026-09-18T10:15:00Z",
  },
  {
    id: "prod-galvanized-razor-wire-cbt65",
    name: "Heavy Galvanized Concertina Razor Wire Coil (CBT-65 / 450mm Diameter)",
    slug: "heavy-galvanized-concertina-razor-wire-coil-450mm",
    categoryId: "cat-security",
    subcategoryId: "sub-razor",
    price: 6500,
    salePrice: 5800,
    stock: 300,
    images: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Hot-dipped heavy galvanized high-tensile concertina razor wire with CBT-65 aggressive blade profile. Deployed on boundary walls of bank branches, government compounds, warehouses, and industrial estates.",
    specifications: {
      "Blade Profile": "CBT-65 (Heavy Cross Type Piercing Blade)",
      "Coil Diameter": "450mm (Expanded length: 9-10 meters per coil)",
      "Tensile Strength": "1450-1550 N/mm² High-Carbon Spring Core Wire",
      "Corrosion Coating": "Hot Dipped Zinc Galvanized (>240 g/m²)",
    },
    features: [
      "Unsurpassed anti-scaling and physical anti-intrusion deterrent",
      "Weather-resistant alloy resisting rust and humid monsoon climates",
      "Supplied with galvanized mounting brackets and tie clips",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN E-SECURITY",
    brand: "Pakistan Cables",
    created_at: "2026-09-16T11:00:00Z",
  },
  {
    id: "prod-perimeter-electric-fencing-energizer",
    name: "Commercial Security Electric Fence Energizer & Anti-Intrusion Alarm System",
    slug: "commercial-security-electric-fence-energizer-system",
    categoryId: "cat-security",
    subcategoryId: "sub-fencing",
    price: 85000,
    salePrice: 78000,
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-voltage non-lethal perimeter electrification system generating up to 9,900V pulses with instant cut/short detection, siren alert, and dry contact integration for CCTV automated PTZ preset triggering.",
    specifications: {
      "Peak Output Voltage": "9,900 Volts (5 Joules Stored Energy)",
      "Perimeter Coverage": "Up to 5 km single wire / 1 km multi-strand fence",
      "Backup Battery": "Integrated 12V 7Ah battery with mains trickle charger",
      "Alarm Triggers": "Wire cut, wire grounding/short, tamper switch",
    },
    features: [
      "Smart zoning keypad with LCD status telemetry",
      "Safe high-voltage pulse cycle complying with IEC 60335 standards",
      "Seamlessly ties into NVR security systems for automated spotlight tracking",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN E-SECURITY",
    brand: "ZKTeco",
    created_at: "2026-09-15T15:30:00Z",
  },
  {
    id: "prod-dahua-5mp-ptz",
    name: "Dahua 5MP Smart Dual Light Active Deterrence PTZ Camera (25x Zoom)",
    slug: "dahua-5mp-smart-dual-light-ptz-camera-25x",
    categoryId: "cat-security",
    subcategoryId: "sub-cctv",
    price: 65000,
    salePrice: 59000,
    stock: 22,
    images: [
      "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Enterprise speed dome PTZ camera featuring 25x optical zoom, perimeter protection, red/blue flashing warning lights, and two-way audio speaker. Ideal for bank yard surveillance and campus perimeters.",
    specifications: {
      "Resolution": "5 Megapixel (2592 × 1944) @ 30fps",
      "Zoom": "25x Optical Zoom (4.8mm - 120mm Motorized Varifocal)",
      "IR Distance": "Up to 100m Smart IR + Warm LED Dual Illuminator",
      "Pan / Tilt Range": "360° Endless Pan, -15° to +90° Tilt",
      "Protection": "IP66 Weatherproof & TVS 6000V Lightning Surge Protection",
    },
    features: [
      "AI human and vehicle auto-tracking functionality",
      "Built-in active siren and strobe light to scare off intruders",
      "MicroSD card slot supporting up to 512GB local storage",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN E-SECURITY",
    brand: "Dahua Technology",
    created_at: "2026-09-21T14:00:00Z",
  },
  {
    id: "prod-dell-latitude-workstation",
    name: "Dell Latitude Commercial Business Workstation (Core i7 / 16GB / 512GB SSD)",
    slug: "dell-latitude-commercial-business-workstation-laptop",
    categoryId: "cat-it",
    subcategoryId: "sub-laptops",
    price: 185000,
    salePrice: 168000,
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Enterprise commercial-grade laptop built for heavy administrative processing, CAD drawings, and surveillance monitoring. Equipped with Intel Core i7 processor, 16GB DDR4 RAM, 512GB NVMe SSD, and fingerprint security.",
    specifications: {
      "Processor": "Intel Core i7 13th Gen Deca-Core Processor",
      "Memory & Storage": "16GB 3200MHz RAM + 512GB PCIe Gen4 NVMe M.2 SSD",
      "Display": "15.6\" FHD (1920x1080) Anti-Glare 300 nits IPS",
      "Security": "TPM 2.0 Hardware Security + Windows Hello Fingerprint",
      "Warranty": "12 Months Official Zohan Parts & Service Warranty",
    },
    features: [
      "Mil-STD 810H military certified rugged chassis durability",
      "ExpressCharge rapid battery refill (80% in 60 minutes)",
      "Wi-Fi 6E and Gigabit RJ-45 LAN port for stable connectivity",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN NETWORKS",
    brand: "D-Link",
    created_at: "2026-09-20T16:00:00Z",
  },
  {
    id: "prod-armored-fiber-12core-roll",
    name: "Outdoor Armored 12-Core Single Mode Optical Fiber Cable (1000m Drum)",
    slug: "outdoor-armored-12-core-single-mode-fiber-cable-drum",
    categoryId: "cat-it",
    subcategoryId: "sub-fiber",
    price: 54000,
    salePrice: 48500,
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Steel tape corrugated armored outdoor single mode G.652D 12-strand optical fiber cable drum. Rodent-proof and crush-resistant for underground duct and aerial institutional installations across campuses and hospital networks.",
    specifications: {
      "Fiber Type": "Single-Mode G.652D 9/125um Low-Water-Peak",
      "Cores": "12 Independent Color-Coded Fiber Strands",
      "Armoring": "Corrugated Steel Tape (CST) Armor + Dual Steel Strength Members",
      "Drum Length": "1,000 Meters (1 KM Continuous Spool)",
    },
    features: [
      "Zero water ingress jelly-filled loose tube construction",
      "Ultra-low attenuation: < 0.36 dB/km at 1310nm",
      "UV-stabilized HDPE outdoor jacket with sequential meter print",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN NETWORKS",
    brand: "Fast Cables",
    created_at: "2026-09-18T08:00:00Z",
  },
  {
    id: "prod-pak-cat7-shielded-drum",
    name: "Pakistan Cables CAT7 S/FTP 10-Gigabit Double Shielded Network Cable (305m)",
    slug: "pakistan-cables-cat7-sftp-10g-shielded-cable-305m",
    categoryId: "cat-it",
    subcategoryId: "sub-catcables",
    price: 46000,
    salePrice: 42000,
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Heavy-duty pure solid copper 23 AWG CAT7 double-shielded network cable roll (Screened Foiled Twisted Pair). Designed for high-interference banking server rooms, industrial switchboards, and 10G data centers.",
    specifications: {
      "Conductor": "100% Electrolytic Oxygen-Free Solid Copper 23 AWG",
      "Bandwidth": "600 MHz Transmission Frequency / 10 Gbps Data Rate",
      "Shielding": "Individual Al-Mylar Foil per pair + Overall Tinned Copper Braid",
      "Drum Length": "305 Meters (1000 Feet) Wooden Reel",
    },
    features: [
      "Near-zero electromagnetic interference (EMI) and crosstalk immunity",
      "LSZH (Low Smoke Zero Halogen) fire-retardant outer jacket",
      "Certified for high-wattage 90W PoE++ Power over Ethernet delivery",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN NETWORKS",
    brand: "Pakistan Cables",
    created_at: "2026-09-19T12:00:00Z",
  },
  {
    id: "prod-ubiquiti-powerbeam-iso",
    name: "Ubiquiti PowerBeam 5AC ISO 500mm 27dBi High-Power Wireless Dish",
    slug: "ubiquiti-powerbeam-5ac-iso-500mm-27dbi-bridge",
    categoryId: "cat-it",
    subcategoryId: "sub-wireless",
    price: 42000,
    salePrice: 38500,
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "High-isolation 500mm parabolic dish bridge with integrated rear shield for extreme RF-noisy environments. Delivers 450+ Mbps TCP/IP throughput over links exceeding 25-30 kilometers line of sight.",
    specifications: {
      "Frequency": "5 GHz (airMAX ac processor with airPrism filtering)",
      "Dish Diameter": "500 mm (27 dBi High Gain Dish)",
      "Range": "30+ KM Point-to-Point Long Distance Backhaul",
      "PoE Power": "24V, 0.5A Gigabit PoE Adapter (Included)",
    },
    features: [
      "Integrated isolator radome blocks RF side lobes and urban interference",
      "Precision elevation and azimuth alignment bracket",
      "Real-time spectrum analyzer airView accessible via smartphone Wi-Fi",
    ],
    isFeatured: true,
    isNew: false,
    department: "ZOHAN NETWORKS",
    brand: "Ubiquiti Networks",
    created_at: "2026-09-17T14:00:00Z",
  },
  {
    id: "prod-anodized-aluminium-profile-glass",
    name: "Architectural Heavy Anodized Aluminium Section & Double Glazed Tempered Glass",
    slug: "architectural-anodized-aluminium-profile-double-glazed-glass",
    categoryId: "cat-construction",
    subcategoryId: "sub-alum-glass",
    price: 450,
    salePrice: 410,
    stock: 2500,
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Commercial building window and curtain walling system. Features 1.6mm - 2.0mm thick anodized bronze/champagne aluminium sections paired with 12mm thermal acoustic double glazed tempered safety glass. Price per square foot.",
    specifications: {
      "Section Thickness": "1.6mm - 2.0mm Heavy Gauge Architectural Grade",
      "Glass Spec": "5mm Clear + 6mm Air Gap + 5mm Tinted Tempered Glass",
      "Finish": "25-Micron Hard Anodized Powder-Coated Finish",
      "Sound Insulation": "Reduces external noise by up to 35 dB",
    },
    features: [
      "High thermal insulation drastically reducing air conditioning bills",
      "EPDM airtight dual rubber gaskets preventing dust and water seepage",
      "Heavy duty stainless steel friction stays and multi-point security locks",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Amreli Steels",
    created_at: "2026-09-19T10:00:00Z",
  },
  {
    id: "prod-ziarat-white-marble-slabs",
    name: "Ziarat Superior Polished White Marble Slabs & Porcelain Floor Tiles",
    slug: "ziarat-superior-polished-white-marble-porcelain-tiles",
    categoryId: "cat-construction",
    subcategoryId: "sub-tiles-marble",
    price: 280,
    salePrice: 250,
    stock: 8000,
    images: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "First-grade natural Ziarat White and Verona Pakistani marble slabs alongside 600x600mm glazed porcelain floor tiles for commercial banks, mosque floors, and residential plazas. Mirror polish finish. Price per square foot.",
    specifications: {
      "Stone Type": "Natural Ziarat White Calcite Marble / Vitrified Porcelain",
      "Thickness": "16mm - 18mm Calibrated Cut Slabs",
      "Surface Finish": "Diamond Polished High-Gloss Mirror Reflection",
      "Water Absorption": "< 0.5% (Frost and stain resistant)",
    },
    features: [
      "Fine crystalline grain with subtle natural veins",
      "High abrasion resistance under intense foot traffic",
      "Uniform calibration ensuring hairline joints during installation",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Zohan Construction Supplies",
    created_at: "2026-09-18T13:00:00Z",
  },
  {
    id: "prod-marine-plywood-structural-timber",
    name: "Commercial Marine Grade Water-Resistant Plywood & Seasoned Wood Timber",
    slug: "commercial-marine-grade-water-resistant-plywood-timber",
    categoryId: "cat-construction",
    subcategoryId: "sub-wooden",
    price: 4800,
    salePrice: 4350,
    stock: 160,
    images: [
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Boiling water resistant (BWR) marine plywood sheets (8x4 ft, 16mm/18mm) and kiln-seasoned deodar/partal structural timber wood. Treated with anti-termite and borate wood preservatives for long-lasting structural carpentry.",
    specifications: {
      "Plywood Grade": "IS:710 Marine Grade BWR with Phenolic Resin",
      "Sheet Dimensions": "8 Feet x 4 Feet (2440mm x 1220mm x 18mm)",
      "Timber Treatment": "Pressure Vacuum Impregnated Anti-Termite Chemical",
      "Moisture Content": "Below 10% Kiln Dried Seasoning",
    },
    features: [
      "Zero delamination even when submerged in standing water",
      "High load-bearing capacity for concrete shuttering and wardrobe carcass",
      "Smooth calibrated sanding on both sides ready for veneer or polish",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-16T09:00:00Z",
  },
  {
    id: "prod-sonex-chrome-brass-bath-mixer-set",
    name: "Sonex Deluxe Solid Brass Chrome Finished Bathroom Sanitary & Shower Set",
    slug: "sonex-deluxe-solid-brass-chrome-sanitary-shower-set",
    categoryId: "cat-construction",
    subcategoryId: "sub-sanitary",
    price: 19500,
    salePrice: 17800,
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Complete heavy cast brass sanitary fitting set including wall-mounted concealed bath mixer, overhead rain shower head, telephonic hand spray, and ceramic disc basin mixer with mirror chrome electroplating.",
    specifications: {
      "Material": "100% Grade A Heavy Virgin Brass Ingot",
      "Cartridge": "Ceramic Disc Cartridge (Tested for 500,000 cycles)",
      "Plating": "Multi-layer Nickel & High-Gloss Chrome Finish",
      "Warranty": "10-Year Leak-Proof Manufacturer Warranty",
    },
    features: [
      "Smooth single-lever operation with precise hot/cold thermal mixing",
      "Corrosion and lime-scale resistant silicone rain shower nozzles",
      "Supplied with brass flanges, wall eccentrics, and Teflon tape",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Master Sanitary",
    created_at: "2026-09-17T16:00:00Z",
  },
  {
    id: "prod-screened-ravi-chenab-river-sand",
    name: "Screened Ravi & Chenab High-Purity River Sand (Bulk Tipper Delivery - 800 Cft)",
    slug: "screened-ravi-chenab-high-purity-river-sand-tipper",
    categoryId: "cat-construction",
    subcategoryId: "sub-sands",
    price: 34000,
    salePrice: 31500,
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Clean mechanical-screened river sand free from organic matter, silt, and saline efflorescence salts. Delivered via 10-wheeler tipper truck (800 Cubic Feet) directly to project construction sites in DG Khan and adjacent tehsils.",
    specifications: {
      "Grain Fineness Modulus": "2.4 - 2.8 Medium-Coarse Concrete Sand",
      "Silt Content": "< 3% Clean Washed and Screened",
      "Volume": "800 Cubic Feet (Approx. 35 Tons per Tipper)",
      "Delivery Mode": "Hydraulic Dumper Tipper Truck On-Site",
    },
    features: [
      "Optimized grain size distribution producing higher concrete compressive strength",
      "Zero salt content prevents plaster blistering and brick discoloration",
      "Uniform bulk moisture content ensuring consistent cement-water ratios",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Zohan Construction Supplies",
    created_at: "2026-09-15T08:00:00Z",
  },
  {
    id: "prod-executive-ballpoint-pens-box",
    name: "Piano & Pilot Executive Smooth-Flow Ballpoint Pen Set (Box of 50 Pcs)",
    slug: "piano-pilot-executive-smooth-flow-ballpoint-pens-box-50",
    categoryId: "cat-stationery",
    subcategoryId: "sub-pens-paper",
    price: 1650,
    salePrice: 1450,
    stock: 200,
    images: [
      "https://images.unsplash.com/photo-1585336261026-7f416fa48cf6?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Commercial bulk pack of 50 high-precision 0.7mm tungsten carbide ballpoint pens. Smudge-free German oil-based ink formulated for continuous fast handwriting on legal ledgers, checkbooks, and official registers.",
    specifications: {
      "Tip Size": "0.7mm Fine Needle Point Tungsten Carbide Ball",
      "Ink Colors": "Blue / Black Executive Document Permanent Ink",
      "Writing Distance": "Exceeds 1,500 meters of continuous ink flow",
      "Packaging": "Box of 50 Pens in protective inner tray",
    },
    features: [
      "Leak-proof barrel design even under atmospheric pressure changes",
      "Ergonomic ribbed rubberized finger grip for fatigue-free signing",
      "Quick-drying archival ink preventing smears on legal paper",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN STATIONARY",
    brand: "Double A",
    created_at: "2026-09-20T11:00:00Z",
  },
  {
    id: "prod-archival-box-files-legal-binders",
    name: "Heavy-Duty Archival Document Box Files & Legal Lever-Arch Binders (Pack of 12)",
    slug: "heavy-duty-archival-document-box-files-lever-arch-binders-12",
    categoryId: "cat-stationery",
    subcategoryId: "sub-filing",
    price: 5400,
    salePrice: 4800,
    stock: 110,
    images: [
      "https://images.unsplash.com/photo-1568667256549-094345857637?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Rigid archival box files and 3-inch spine lever-arch document binders with metal shoe reinforcement, finger pull ring, and internal compressor bar. Manufactured to store heavy legal cases and bank accounting records for decades.",
    specifications: {
      "Spine Width": "75mm (Holds up to 500 sheets of 80 GSM paper)",
      "Board Thickness": "2.2mm Heavy Solid Calendered Strawboard",
      "Mechanism": "Heavy Gauge Chrome Plated Lever Arch Clip with Rado Locking",
      "Quantity": "Master Carton of 12 Files",
    },
    features: [
      "Reinforced metal edge protector corners preventing shelf wear and tear",
      "Reversible spine label pocket for easy indexing and retrieval",
      "Acid-free internal lining preventing paper degradation over time",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN STATIONARY",
    brand: "Deli",
    created_at: "2026-09-18T15:00:00Z",
  },
  {
    id: "prod-universal-laser-toner-cartridge",
    name: "High-Yield Black Laser Printer Toner Cartridge (Compatible with HP/Canon/Xerox)",
    slug: "high-yield-black-laser-printer-toner-cartridge",
    categoryId: "cat-stationery",
    subcategoryId: "sub-printing",
    price: 4200,
    salePrice: 3750,
    stock: 85,
    images: [
      "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Premium micro-refined toner cartridge delivering crisp, deep black text and sharp graphics without background shading or drum streaking. High-capacity yield of up to 3,000 standard test pages at 5% coverage.",
    specifications: {
      "Page Yield": "Up to 3,000 Pages (ISO/IEC 19752 Standard)",
      "Toner Powder": "Polymerized Chemical Micro-Toner (Deep Black)",
      "Compatibility": "HP LaserJet Pro, Canon LBP Series, Xerox WorkCentre",
      "OPC Drum": "Long-Life Multi-Cycle Photoreceptor Drum",
    },
    features: [
      "Zero toner scattering and clean magnetic roller pickup",
      "Protects printer fuser sleeves from premature burnout",
      "Individually sealed in static-free airbag packaging",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN STATIONARY",
    brand: "Double A",
    created_at: "2026-09-17T10:00:00Z",
  },
  {
    id: "prod-conference-table-10p",
    name: "Interwood Executive 10-12 Person Boardroom Conference Table with Cable Raceway",
    slug: "interwood-executive-10-person-boardroom-conference-table",
    categoryId: "cat-furniture",
    subcategoryId: "sub-conference",
    price: 185000,
    salePrice: 165000,
    stock: 5,
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Prestigious 12-foot executive boardroom meeting table crafted from thermo-fused walnut melamine top with heavy steel base and central aluminum pop-up multimedia connectivity hubs for HDMI, LAN, and power sockets.",
    specifications: {
      "Dimensions": "12 Feet x 4 Feet x 2.5 Feet (3600mm x 1200mm x 750mm)",
      "Top Surface": "36mm Heavy Beveled Edge Scratch-Resistant Laminate",
      "Wire Management": "Dual Brushed Aluminum Pop-Up Power/Data Modules",
      "Capacity": "Seats 10 to 12 Executive Directors comfortably",
    },
    features: [
      "Internal hollow legs conceal cabling from floor to tabletop",
      "Stain-resistant surface impervious to hot tea and sanitizer spills",
      "Reinforced heavy-gauge structural steel subframe prevents sagging",
    ],
    isFeatured: true,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-21T08:00:00Z",
  },
  {
    id: "prod-german-laminate-wooden-flooring",
    name: "Commercial AC4 Heavy-Traffic HDF German Laminate Wooden Flooring (Per Sq. Ft.)",
    slug: "commercial-ac4-heavy-traffic-hdf-wooden-flooring",
    categoryId: "cat-furniture",
    subcategoryId: "sub-flooring",
    price: 260,
    salePrice: 235,
    stock: 6500,
    images: [
      "https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "8mm / 12mm high-density fiberboard (HDF) click-lock laminate wooden flooring with AC4 commercial wear layer. Resistant to office chair casters, cigarette burns, and water splashes. Includes silent foam underlayment. Price per sq. ft.",
    specifications: {
      "Traffic Rating": "AC4 / Class 32 Commercial High Traffic",
      "Core Material": "900+ kg/m³ High Density Moisture-Resistant HDF",
      "Plank Size": "1215mm x 195mm x 8.3mm with V-Groove Micro Bevel",
      "Locking System": "Uniclic Patented Tool-Free Interlocking System",
    },
    features: [
      "Anti-bacterial and anti-static surface repelling dust and allergens",
      "Wax-sealed click joints for enhanced water resistance",
      "Compatible with underfloor heating systems and quick room installation",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-16T13:00:00Z",
  },
  {
    id: "prod-fireproof-steel-filing-cabinet",
    name: "Heavy 20-Gauge Cold Rolled Steel 4-Drawer Fireproof Office Filing Cabinet",
    slug: "heavy-steel-4-drawer-fireproof-office-filing-cabinet",
    categoryId: "cat-furniture",
    subcategoryId: "sub-cabinets",
    price: 48000,
    salePrice: 43500,
    stock: 16,
    images: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Heavy-duty commercial filing cabinet built with 20-gauge cold rolled steel sheets. Features central master locking system with dual keys, heavy-duty ball bearing drawer slides, and anti-tilt safety counterweight mechanism.",
    specifications: {
      "Material": "Cold Rolled Steel (0.8mm - 1.0mm thickness)",
      "Drawers": "4 Full-Extension Deep Filing Drawers with Label Holders",
      "Dimensions": "52\" Height x 18\" Width x 24\" Depth",
      "Locking Mechanism": "Central Gang Lock System with 2 Master Keys",
      "Drawer Load": "Tested for up to 45 kg per drawer",
    },
    features: [
      "Anti-tilt interlock prevents opening multiple heavy drawers simultaneously",
      "Electrostatic powder-coated scratch-resistant matte finish",
      "Accepts both Legal and A4 size hanging folder files",
    ],
    isFeatured: false,
    isNew: false,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-17T15:00:00Z",
  },
  {
    id: "prod-ergonomic-staff-task-chair",
    name: "Interwood Mid-Back Ergonomic Breathable Mesh Office Staff Task Chair",
    slug: "interwood-mid-back-ergonomic-staff-task-chair",
    categoryId: "cat-furniture",
    subcategoryId: "sub-chairs",
    price: 21500,
    salePrice: 18900,
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1580481077195-c3a821a58875?q=80&w=1000&auto=format&fit=crop",
    ],
    description: "Ergonomic mid-back computer chair designed for long corporate working shifts. Features contoured lumbar curve, pneumatic height adjustment gas lift, 360-degree swivel, and nylon caster wheels for hard and carpeted floors.",
    specifications: {
      "Mechanism": "Tilt Tension Lock Mechanism with 1-lever Control",
      "Gas Lift": "Class 3 Heavy-Duty Pneumatic Nitrogen Piston",
      "Seat Cushion": "High-Resilience Cold-Cured Molded Foam",
      "Weight Tested": "Up to 125 kg Continuous Working Capacity",
    },
    features: [
      "Tear-resistant breathable nylon mesh back prevents heat buildup",
      "Reinforced heavy-duty 5-star nylon base with smooth gliding casters",
      "Compact footprint ideal for dense modular workstation arrangements",
    ],
    isFeatured: false,
    isNew: true,
    department: "ZOHAN CONSTRUCTIONS",
    brand: "Interwood",
    created_at: "2026-09-19T17:00:00Z",
  },
];

export const INITIAL_BANNERS: HeroBanner[] = [
  {
    id: "banner-1",
    title: "Enterprise E-Security & 4K Surveillance",
    subtitle: "Authorized Hikvision, Dahua & ZKTeco Partner",
    description: "Commercial-grade 4K ColorVu IP CCTV, multi-zone walkthrough security gates, biometric access control & smart fire suppression systems.",
    badge: "12-Month Replacement Warranty • NTN: 7539474-3",
    ctaText: "Explore Security Gear",
    ctaLink: "/shop/security",
    secondaryCtaText: "Request Corporate Quote",
    secondaryCtaLink: "/contact",
    imageUrl: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=1600&auto=format&fit=crop",
    active: true,
    displayOrder: 1,
  },
  {
    id: "banner-2",
    title: "High-Capacity Enterprise IT & Fiber Networking",
    subtitle: "Ubiquiti Networks, D-Link & Fast Cables Official Solutions",
    description: "Long-range airMAX wireless backhaul bridges, 10G optical fiber distribution, managed gigabit PoE switches, and server infrastructure.",
    badge: "Official Brand Partners",
    ctaText: "Discover IT Solutions",
    ctaLink: "/shop/it-products",
    secondaryCtaText: "Speak With Engineer",
    secondaryCtaLink: "/contact",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1600&auto=format&fit=crop",
    active: true,
    displayOrder: 2,
  },
  {
    id: "banner-3",
    title: "Premium Construction Supplies & Multani Bricks",
    subtitle: "Authentic Kiln-Fired Bricks, Interlocking Tuff Tiles & Sanitaryware",
    description: "First-class Awal Multani red clay bricks, heavy-duty industrial tuff tiles, Ziarat marble, and luxury sanitaryware supplied direct to site.",
    badge: "Direct Kiln-Fired & Certified Supplies",
    ctaText: "View Building Supplies",
    ctaLink: "/shop/construction",
    secondaryCtaText: "Bulk Quotation",
    secondaryCtaLink: "/contact",
    imageUrl: "https://images.unsplash.com/photo-1541888946425-d0fbb18615f8?q=80&w=1600&auto=format&fit=crop",
    active: true,
    displayOrder: 3,
  },
  {
    id: "banner-4",
    title: "Ergonomic Corporate Office Furniture",
    subtitle: "Authorized Interwood Partner - Seating, Workstations & Cabinets",
    description: "Orthopedic high-back executive chairs, modular 4-person workstations, boardroom conference tables, and fireproof archival cabinets.",
    badge: "Turnkey Corporate Fit-Out",
    ctaText: "Browse Office Furniture",
    ctaLink: "/shop/office-furniture",
    secondaryCtaText: "WhatsApp Inquiry",
    secondaryCtaLink: "/contact",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1600&auto=format&fit=crop",
    active: true,
    displayOrder: 4,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "c-1",
    code: "WELCOME10",
    type: "percentage",
    value: 10,
    minSpend: 2000,
    active: true,
    expiryDate: "2027-12-31",
  },
  {
    id: "c-2",
    code: "ZOHAN500",
    type: "fixed",
    value: 500,
    minSpend: 5000,
    active: true,
    expiryDate: "2027-12-31",
  },
  {
    id: "c-3",
    code: "BULK15",
    type: "percentage",
    value: 15,
    minSpend: 20000,
    active: true,
    expiryDate: "2027-12-31",
  },
];

export const CORPORATE_CLIENTS = [
  { name: "MCB Bank Ltd.", category: "Banking Sector" },
  { name: "Zarai Taraqiati Bank (ZTBL)", category: "Development Banking" },
  { name: "Silk Bank Ltd.", category: "Commercial Banking" },
  { name: "Habib Bank Limited (HBL)", category: "Premier Banking" },
  { name: "United Bank Limited (UBL)", category: "Commercial Banking" },
  { name: "PTCL DG Khan", category: "Telecom Infrastructure" },
  { name: "Mobilink (Jazz)", category: "Cellular Network" },
  { name: "Wateen Telecom", category: "Data & Fiber" },
  { name: "Doctors Hospital DG Khan", category: "Healthcare Infrastructure" },
  { name: "DHQ Hospital DG Khan", category: "Public Healthcare" },
  { name: "Pharmevo Pharmaceuticals", category: "Pharma Manufacturing" },
  { name: "Fauji Cement Company Ltd.", category: "Industrial Manufacturing" },
  { name: "CRDI", category: "Development & Research" },
  { name: "DG Khan Gymkhana Club", category: "Hospitality & Sports" },
  { name: "Sinoma International", category: "Engineering & Construction" },
];

export const BRAND_PARTNERS = [
  { name: "Hikvision", role: "Video Surveillance Systems", logoText: "HIKVISION" },
  { name: "Dahua Technology", role: "AI Security & Cameras", logoText: "dahua" },
  { name: "Ubiquiti Networks", role: "airMAX & Enterprise Wireless", logoText: "UBIQUITI" },
  { name: "ZKTeco", role: "Biometrics & Walkthrough Gates", logoText: "ZKTECO" },
  { name: "D-Link", role: "Enterprise Switching & Routers", logoText: "D-Link" },
  { name: "Fast Cables", role: "Pure Copper Network & Power", logoText: "FAST CABLES" },
  { name: "Interwood", role: "Corporate Furniture & Workstations", logoText: "INTERWOOD" },
  { name: "Pakistan Cables", role: "Certified Wiring Solutions", logoText: "PAKISTAN CABLES" },
  { name: "Amreli Steels", role: "Structural Steel Bars", logoText: "AMRELI STEELS" },
  { name: "Mughal Steel", role: "Earthquake Resistant Rebars", logoText: "MUGHAL STEEL" },
];
